using MAD_Keuzedeel.env;
using MAD_Keuzedeel.Models;
using MAD_Keuzedeel.Stores;
using System.Threading.Tasks;

public static class AuthorizationUtils
{
    /// <summary>
    /// Generates the authorization URI for the OAuth 2.0 authorization code flow with PKCE.
    /// </summary>
    /// <param name="pkceData">A dictionary containing PKCE parameters, including <c>state</c> and <c>code_challenge</c>, typically generated by <c>PkceUtils.GeneratePkceData()</c>.</param>
    /// <returns>The authorization URI as a string.</returns>
    public static Uri GenerateAuthUri(Dictionary<string, string> pkceData)
    {
        return new Uri(
            $"{OAuth.AuthorizeUrl}" +
            $"?client_id={OAuth.ApplicationId}" +
            $"&redirect_uri={OAuth.RedirectUri}" +
            $"&response_type=code" +
            $"&scope=openid read_user" +
            $"&state={pkceData["state"]}" +
            $"&code_challenge={pkceData["code_challenge"]}" +
            $"&code_challenge_method=S256"
        );
    }

    /// <summary>
    /// Generates the request data dictionary required for exchanging an authorization code for an access token.
    /// </summary>
    /// <param name="token">The authorization code received from the authorization server.</param>
    /// <param name="verifier">The PKCE code verifier corresponding to the authorization request, typically generated by <c>PkceUtils.GeneratePkceData()</c>.</param>
    /// <param name="grantType">The type of grant being used. Defaults to <c>"authorization_code"</c>.</param>
    /// <returns>A dictionary containing the required parameters for the token request.</returns>
    public static Dictionary<string, string> GenerateRequestData(string token, string verifier)
    {
        return new Dictionary<string, string>
            {
                { "client_id", OAuth.ApplicationId },
                { "client_secret", OAuth.SecretKey },
                { "code", token },
                { "code_verifier", verifier },
                { "grant_type", "authorization_code" },
                { "redirect_uri", OAuth.RedirectUri }
            };
    }

    /// <summary>
    /// Generates the request data dictionary required for exchanging a refresh token for a new access token.
    /// </summary>
    /// <param name="refreshToken">The refresh token previously obtained from the authorization server.</param>
    /// <returns>A dictionary containing the required parameters for the refresh token request.</returns>
    public static Dictionary<string, string> GenerateRefreshData(string refreshToken)
    {
        return new Dictionary<string, string>
            {
                { "client_id", OAuth.ApplicationId },
                { "client_secret", OAuth.SecretKey },
                { "refresh_token", refreshToken },
                { "grant_type", "refresh_token" },
                { "redirect_uri", OAuth.RedirectUri }
            };
    }

    /// <summary>
    /// Checks if the user is currently authorized by verifying the presence of both authentication and user data in secure storage.
    /// </summary>
    /// <returns>A bool indicating whether the user is authorized.</returns>
    public static async Task<bool> IsAuthorised()
    {
        Auth? auth = await AuthStore.Load();
        User? user = await UserStore.Load();

        return !(string.IsNullOrEmpty(auth.id_token) || string.IsNullOrEmpty(user.name));
    }
}
